name: ACC Connector release

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    release:
        name: Build release tag
        runs-on: windows-latest
        steps:
            - name: Grab version
              run: |
                TAG=${{ github.event.release.tag_name }}
                echo "VERSION=${TAG#v}" >> $GITHUB_ENV
              shell: bash
            - name: Checkout
              uses: actions/checkout@v2
              with:
                submodules: 'true'
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2
            - name: Build app
              run: |
                msbuild /t:publish /restore /p:PublishProfile=FolderProfile /property:Configuration=Release
            - name: Create installer
              run: |
                "%programfiles(x86)%/Inno Setup 6/iscc.exe" acc-connector.iss /DAppVer=${{ env.VERSION }}
              shell: cmd
            - name: Upload installer
              run: |
                gh release upload ${{ github.event.release.tag_name }} Output/ACC-Connector-Setup-${{ env.VERSION }}.exe
              env:
                GH_TOKEN: ${{ github.token }}
