name: Build installer

on:
    workflow_call:
        inputs:
            app_version:
                description: Version of the application
                type: string
                default: "0.0.0"

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: 'true'
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2
            - name: Update DLL version
              run: |
                client-hooks/makever.ps1 ${{ inputs.app_version }} client-hooks/version.h
            - name: Build app
              run: |
                msbuild /t:publish /restore /p:PublishProfile=FolderProfile /property:Configuration=Release /property:Version=${{ inputs.app_version }}
            - name: Create installer
              run: |
                "%programfiles(x86)%/Inno Setup 6/iscc.exe" acc-connector.iss /DAppVer=${{ inputs.app_version }}
              shell: cmd
            - name: Upload installer
              uses: actions/upload-artifact@v4
              with:
                name: app_installer
                path: Output/ACC-Connector-Setup-${{ inputs.app_version }}.exe
