name: Build and upload release

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    version:
        name: Set up release version
        runs-on: windows-latest
        steps:
            - id: version
              name: Grab version
              run: |
                TAG=${{ github.event.release.tag_name }}
                echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
              shell: bash
        outputs:
            version: ${{ steps.version.outputs.version }}
    build:
        needs: version
        name: Build app
        uses: ./.github/workflows/build.yaml
        with:
            app_version: ${{ needs.version.outputs.version }}
    release:
        needs: [version, build]
        name: Upload installer
        runs-on: windows-latest
        steps:
            - name: Download installer
              uses: actions/download-artifact@v4
              with:
                name: app_installer
            - name: Upload installer to release
              run: |
                gh release upload --repo ${{ github.repository }} ${{ github.event.release.tag_name }} ACC-Connector-Setup-${{ needs.version.outputs.version }}.exe
              env:
                GH_TOKEN: ${{ github.token }}
